description: >
  tfsec container executor
docker:
  - image: "liamg/tfsec:<<parameters.tag>>"
parameters:
  tag:
    default: latest
    description: >
      Pick a specific liamg/tfsec image tag:
      https://hub.docker.com/r/liamg/tfsec/tags
    type: string
